[project]
name = "dbt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-core>=1.10.5",
    "dbt-trino>=1.9.3",
    "trino>=0.335.0",
]
