services:


  postgres:
    image: postgres
    user: "${UID}:${GID}"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: metastore_db
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/postgres_volume/:/var/lib/postgresql/data/
      - ${PWD}/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql


  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ${PWD}/minio_volume/:/data/


  minio_init:
      image: minio/mc
      depends_on:
        - minio
      entrypoint: >
        /bin/sh -c "
        /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
        /usr/bin/mc mb myminio/data;
        exit 0;
        "


  trino:
    image: trinodb/trino
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}/iceberg.properties:/etc/trino/catalog/iceberg.properties
    environment:
      DEBUG: "true"
