default:
  target: default
  outputs:
    default:
      type: trino
      host: trino.127.0.0.1.nip.io
      port: 443
      database: mydata
      schema: dbt
      method: oauth
      verify: false
