
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

seeds:
  - name: country
    description: "A seed file for country data"
    config:
      schema: seeds
    columns:
      - name: country_code
        description: "The country code"
        data_tests:
          - unique
          - not_null
      - name: country_name
        description: "The country name"
        data_tests:
          - not_null