[project]
name = "data-product-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.119.1",
    "pydantic>=2.12.2",
    "python-keycloak>=5.8.1",
    "requests>=2.32.5",
    "uvicorn>=0.38.0",
]
